Add files via upload
Here is the progress I made tonight. See the issue with passing the variable from one function to the next?

NameError: global name 'choice' is not defined

So it's not passing it to the public